### ISSUE TITLE
Where to install Express?

### ISSUE THREAD

**Issue by simonh1000** [mikeumus/docpad-plugin-basicauth#4]
Hi, I need to add authentication to a page on my site so that data can be added to a database used for rendering. I was going to use your plugin until I realised that it uses Express, which is not installed by default by Docpad.

Would it be possible to add it just to your plugin directory, or will it need to be in the main docpad setup, and will I then need to change all my root configuration info?

**Comment by mikeumus** [comment]
Hey @simonh1000, express is a dependency of DocPad and is inherit inside it. The plugin should simply work out of the box. Please let me know your experience in trying it out and I'll be here to help with your implementation.

**Comment by simonh1000** [comment]
Hi there. The error I'm getting is:
`TypeError: Object function app(req, res, next){ app.handle(req, res, next); } has no method 'basicAuth' at basicAuthPlugin.serverExtend`
Feels like the plugin is not being initialised properly, but it is hard to test as it crashes before I can get node-inspector up and running. Any thoughts?

What I have done is install using `docpad install` and copied the lines from your docpad.coffee into the main one. I see that you had a similar issue and I tried swapping express, server in your code but that did not help, and I can't understand how to read the 4 options mentioned in http://docpad.org/docs/events

**Comment by mikeumus** [comment]
Is your project open on GitHub and I'll take a look?

**Comment by simonh1000** [comment]
https://github.com/simonh1000/toonoisy - tell me if that is enough of the project

**Comment by mikeumus** [comment]
Yeah look like enough to go off. First thing I notice is the indenting here on line 82 od docpad.coffee: https://github.com/simonh1000/toonoisy/blob/master/docpad.coffee#L82

Coffeescript is super picky about it's indentations so you'll want the `basicAuth:` properties to have the same spacing or tabbing that `uploadfile` and `fileupload` have there.

**Comment by simonh1000** [comment]
Thanks Michael, I have corrected that but it is not making a difference - any more ideas.
(If I have the right config now, I will happily provide you with a pull for your readme as that is not compatible with my understanding of what you recommend)

**Comment by simonh1000** [comment]
OK, I can get docpad to run if I replace `basicAuth` with `basicauth` in docpad.coffee, but then it does not compile the coffeescript. :-(

**Comment by mikeumus** [comment]
Ok, pardon, I just noticed something. The `basicAuth:` needs to be on the same tab/space level as the `enabledPlugins:` as seen in the readme.

**Comment by simonh1000** [comment]
OK, but now I have a different problem - my express instance has no basicAuth method!
Any ideas?
![image](https://f.cloud.github.com/assets/5256724/2180287/b3bfb07e-970e-11e3-83bc-7203290aa56f.png)

**Comment by simonh1000** [comment]
Hi, I followed some instructions from Balupton that did something similar, and there he suggested doing require("express") instead of trying to extract from opts, and that seemed to fix it. Maybe something has changed since you wrote your plugin?

**Comment by mikeumus** [comment]
Cool, is this in your repo linked above or would you mind showing me how/where you used require("express") exactly in hope that I may iterate/patch the plugin or a pull-request is always welcome too of course. Thank you @simonh1000

**Comment by simonh1000** [comment]
```
express = require('express') 
authMiddleware = express.basicAuth (user, pass) -> 
    return user is 'super' and pass is 'secret'
docpadConfig = {


plugins:
    basicAuth:
        protectedPage: '/gigsadmin.html'
        user: 'testUser'
        pass: 'testPass'

events:
    serverExtend: (opts) ->
        docpad = @docpad

        opts.serverExpress.use (req,res,next) =>
            cleanUrl = req.url.replace(/\?.*/,'')
            file = docpad.getFileByUrl(req.url) or docpad.getFileByUrl(cleanUrl)

            return next()  unless file?.get('protected')

            return authMiddleware(req,res,next)
}
module.exports = docpadConfig
```

**Comment by mikeumus** [comment]
Bingo! :+1:
