### ISSUE TITLE
TypeError: Cannot read property 'user' of undefined

### ISSUE THREAD

**Issue by austinkettner** [mikeumus/docpad-plugin-basicauth#5]
I was wondering why this might be occurring? I installed it as suggested but I am running into the following error `TypeError: Cannot read property 'user' of undefined` when starting up Docpad.

Any help would be appreciated.

**Comment by mikeumus** [comment]
Hey @austinkettner, thanks for using the @DocPad basicAuth plugin. 
Does it tell what line of what file the error is coming from? Also does your project happen to be on GitHub that I may review it?

**Comment by austinkettner** [comment]
The error is 
`TypeError: Cannot read property 'user' of undefined
    at basicAuthPlugin.serverExtend (/Users/austinkettner/Code/glancesapp.com/node_modules/docpad-plugin-basicauth/basicauth.plugin.coffee:25:49)`

I uploaded it into a new repo for you to check out. https://github.com/austinkettner/glancesapp.com

Thanks in advance for any help.

**Comment by mikeumus** [comment]
I'm setting up a GitHub Pages example for basicAuth and am running into the same issue. I'll keep you posted. Express or more likely @DocPad has changed, is a possible culprit. 

Yeah I'm going to need a little more time looking into this. Give me a day or two.

**Comment by mikeumus** [comment]
Hey @balupton, we're having this issue that we can't get to to the `basicauth.user` from the config with what we used to use. Maybe after this commit to @DocPad: https://github.com/bevry/docpad/commit/4e2a5631874bf643b8dae75f9b5c2bfe47d9dcc2

**Comment by mikeumus** [comment]
Hey @austinkettner, any luck now :question:
