### ISSUE TITLE
License!?

### ISSUE THREAD

**Issue by nfriedly** [mikeumus/docpad-plugin-basicauth#9]
I was asked to check on the licenses of the things that my project depends on and I just realized that docpad-plugin-basicauth doesn't have a license named, which means that I won't actually be able to use it until that changes.

DocPad uses the MIT license, and that's what I would recommend, but if you'd like to choose one for yourself, you can see a fine list at http://opensource.org/licenses/ and also a nice guide at http://www.zdnet.com/blog/burnette/howto-pick-an-open-source-license-part-1/130

**Comment by mikeumus** [comment]
Good call @nfriedly. Do you think including the license in the ReadMe is proper enough. Having it's own LICENSE.md file would be a little overkill for this simple plugin I feel.

**Comment by nfriedly** [comment]
Yea, I just putting it in the readme would be good enough. You might also want to put a `"license": "MIT",` (or whatever) line in package.json so that npm and other tools can pick it up automatically.

**Comment by mikeumus** [comment]
Alright I've added it. Just need to republish now.. :snail: 
Thanks again @nfriedly! :smile:

**Comment by nfriedly** [comment]
Awesome, thanks!
